### PR TITLE
Removing old/not maintained plugins

### PR DESCRIPTION
**Pull request by MrGKanev**
I have read the "Contribution Guidelines" but it would have taken ages to create the needed PR-s for every single plugin.

Removed plugins which are:
* Permanently removed from Wordpress.org
* Not updated in 3 or more years
* Combined with another plugin
* Plugin is implemented into the WP Core

This PR is connected with #13 .

### CODE REVIEW

**Comment by ihorvorotnov** [comment]
> - Not updated in 3 or more years
> - Combined with another plugin

I'm not sure these criteria are very accurate and representative. 

Some plugins just don't require updates, they just work. E.g. those that force using Memcached instead of Memcache. There's nothing to update in the plugin, so there are no updates for years - and that's fine.

Being a small, separate plugin that does just one thing (as opposed to be combined with another plugin) is actually a good thing. Many people prefer this type of plugins instead of "all-in-one" types, so removing them from the list just because the functionality is available in another, bigger plugin doesn't feel right, imho.

**Comment by MrGKanev** [comment]
> > * Not updated in 3 or more years
> > * Combined with another plugin
> 
> I'm not sure these criteria are very accurate and representative.
> 
> Some plugins just don't require updates, they just work. E.g. those that force using Memcached instead of Memcache. There's nothing to update in the plugin, so there are no updates for years - and that's fine.
> 
> Being a small, separate plugin that does just one thing (as opposed to be combined with another plugin) is actually a good thing. Many people prefer this type of plugins instead of "all-in-one" types, so removing them from the list just because the functionality is available in another, bigger plugin doesn't feel right, imho.

1. When I meant "Combined with another plugin" it meant something like this: the plugin helped another plugin out but after some updates, it added that functionality, and there is no need for the plugin anymore. I haven't removed plugins just because they do one thing.

2. "Not updated in 3 or more years" - if someone left a  "Review", saing it worked I have left them in. I have mainly removed the ones which don't have any activity at all or personally I know they don't work.

I'm sure the list isn't perfect and there are a few false positives, but the bulk of the plugins which "are removed" or "are going to bug your websites more than help" has been removed. :)

**Comment by lukecav** [comment]
Updated https://github.com/lukecav/awesome-wp-speed-up/blob/main/CONTRIBUTING.md

**Comment by ihorvorotnov** [comment]
Thanks for the clarification @MrGKanev, that makes sense 👍🏼

**Pull request merged**
